FROM node:latest as builder

# Create working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# Set PATH env
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Update npm
RUN npm i -g npm

# Run additional module optimization
RUN apt-get update
RUN apt install ffmpeg -y

# For experimental
RUN apt install -y vim

# Copy sources to working directory
COPY . /usr/src/app

# Install node modules
RUN npm install

# Open necessary ports
EXPOSE 8080
EXPOSE 3033
EXPOSE 3478
EXPOSE 3478/udp
EXPOSE 19302
EXPOSE 19302/udp

# Launch nginx
CMD ["node", "index.js"]